"""no cascade deletions

Revision ID: 28d8ca125ed6
Revises: 3adb0ecab77f
Create Date: 2020-11-08 23:08:18.707707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d8ca125ed6'
down_revision = '3adb0ecab77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'time_of_visit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('time_of_visit', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
