"""time of visit column

Revision ID: 3adb0ecab77f
Revises: b122769b7f4b
Create Date: 2020-11-08 22:52:40.550293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adb0ecab77f'
down_revision = 'b122769b7f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('time_of_visit', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'time_of_visit')
    # ### end Alembic commands ###
